[Blocked by: CPS-2730 (Refactor docker-compose structure)]Update DMI plugin CSITs if needed to use healthchecks
- Updated healthcheck in docker-compose.yml.
- Ensured curl is used properly to check SDNC readiness via the HealthCheck API.
- Added error handling to print "SDNC not ready" if the response is not 200.
- Improved debugging by allowing logs to indicate health check failures.

Issue-ID: CPS-2646
Change-Id: I1b7757fbb529022198c5a41352c2a8b1a3b9da33
Signed-off-by: sourabh_sourabh <sourabh.sourabh@est.tech>

diff --git a/csit/plans/dmi/sdnc/docker-compose.yml b/csit/plans/dmi/sdnc/docker-compose.yml
--- a/csit/plans/dmi/sdnc/docker-compose.yml
+++ b/csit/plans/dmi/sdnc/docker-compose.yml
@@ -62,6 +62,26 @@ services:
       - ./certs/certs.properties:/opt/opendaylight/certs/certs.properties
       - ./certs/keys0.zip:/opt/opendaylight/certs/keys0.zip
 
+
+    healthcheck:
+      test: |
+        response=$(curl --write-out '%{http_code}' --silent --output /dev/null \
+          -H "Authorization: Basic YWRtaW46S3A4Yko0U1hzek0wV1hsaGFrM2VIbGNzZTJnQXc4NHZhb0dHbUp2VXkyVQ==" \
+          -X POST -H "X-FromAppId: csit-sdnc" -H "X-TransactionId: csit-sdnc" \
+          -H "Accept: application/json" -H "Content-Type: application/json" \
+          http://localhost:8181/restconf/operations/SLI-API:healthcheck);
+        if [ "$response" == "200" ]; then
+          echo "✅ SDNC is healthy!"
+          exit 0
+        else
+          echo "❌ SDNC is not responding! Health check failed."
+          exit 1
+        fi
+      interval: 30s
+      timeout: 10s
+      retries: 20
+      start_period: 60s
+
     dns:
       - ${DNS_IP_ADDR-10.0.100.1}
     logging:
